### ISSUE TITLE
Missing warning when compiling two antennas for baseband folder

### ISSUE THREAD

**Issue by McFrappe** [uu-core/wcnes-project2023#6]
See backscatter.pio in commit: https://github.com/uu-core/wcnes-project2023/commit/4587558b975dcde7bee0bdbe774b56d90656186f

**Comment by tobmag** [comment]
Great job finding the error and thank you for opening the issue!

Commit [d92099c ](https://github.com/uu-core/wcnes-project2023/commit/d92099c1c053666f2cb07ce8c752c220d7a2d753) should solve the problem. 
It was an issue when splitting up the total delay over a number of instructions, which was implemented differently in C. So it should have only affected the Python script.

Please close the issue after confirming that the new script is working correctly at your settings.

**Comment by McFrappe** [comment]
@tobmag verified that it works now! Thanks!
