### ISSUE TITLE
Index issue in analysis script (Reliability code)

### ISSUE THREAD

**Issue by Ananthu-uu** [uu-core/wcnes-project2023#7]
![image](https://user-images.githubusercontent.com/128800841/234825140-e224de3b-35c1-4724-981d-a0164a3d4638.png)
[log6.txt](https://github.com/uu-core/wcnes-project2023/files/11342045/log6.txt)

**Comment by McFrappe** [comment]
![image](https://user-images.githubusercontent.com/17787601/234831139-47d4bbf1-b328-411a-84a3-a9f4ac07a525.png)
Also getting error when running a file that contains 5000 packets received. See here following [file](https://github.com/uu-core/wcnes-project2023/blob/4587558b975dcde7bee0bdbe774b56d90656186f/stats/logs/1m_launch_firefly_2/76_54_96k)

**Comment by Frewacom** [comment]
The changes in 384aa1b should fix the issue, but the results are not exactly the same as the ones produced by the code currently in the main branch. In general, it seems to be off by around 0.05%.
